//FOR VARIABLES & Long Prayers
//Maybe use a separate class for responsory portions
var vMary ="Hail Mary, Full of Grace, The Lord is with thee. Blessed art thou amongst women, and blessed is the fruit of thy womb, Jesus. Holy Mary, Mother of God, pray for us sinners now, and at the hour of our death. Amen."
var vFather = "Our Father, who art in heaven, hallowed be thy name. Thy kingdom come, thy will be done, on earth, as it is in heaven. Give us this day our daily bread and forgive us our trespasses as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen."
var vContrition = "O my God, I am heartily sorry for having offended You, and I detest all my sins because I dread the loss of heaven and the pains of hell; but most of all because they offend You, my God, You Who are all good and deserving of all my love. I firmly resolve, with the help of Your grace, to confess my sins, to do penance, and to amend my life. Amen."
var vMartyrQueen = "Queen of Martyrs, your heart suffered so much. I beg you, by the merits of the tears you shed in these terrible and sorrowful times, to obtain for me and all the sinners of the world the grace of complete sincerity and repentance. Amen."
var vIntroRosary = "My God, I offer You this rosary for Your glory, so I may honor Your Holy Mother, the Blessed Virgin, so I can share and meditate upon her suffering. I humbly beg You to give me true repentance for all my sins. Give me wisdom and humility so that I may receive all the indulgences contained in this prayer."

var vPromOpen = "Promises to St. Bridget:<br>According to St. Bridget of Sweden, seven promises were made to those who meditate on Our Lady’s Tears and Sorrows. The Blessed Virgin grants seven graces to the souls who honour her daily by saying seven Hail Marys while meditating on her tears and Sorrows. These are:"

var vMercyMother = "Most merciful mother, remind us always about the sorrows of your son, Jesus."

var vConceived = "Mary, who was conceived without sin and who suffered for us, pray for us."
 
var sevensorrows = {
  swordstitles:{
    1: "The Prophecy of Simeon",
    2: "The Flight into Egypt",
    3: "The Loss of Jesus in the Temple",
    4: "Mary Meets Jesus on the Way to Calvary",
    5: "Mary Stands at the Foot of the Cross", 
    6: "Mary Receives the Dead Body of Jesus in Her Arms",
    7: "Jesus Is Placed in the Tomb",
  }

  swordsintros:{
    1: "The First Sorrowful Mystery: ",
    2: "The Second Sorrowful Mystery: ",
    3: "The Third Sorrowful Mystery: ",
    4: "The Fourth Sorrowful Mystery ",
    5: "The Fifth Sorrowful Mystery ",
    6: "The Sixth Sorrowful Mystery ",
    7: "The Seventh Sorrowful Mystery "
  }

  swordsverses: {
    1: " Luke 2:22-35",
    2: " Matthew 2:13-15",
    3: " Luke 2:41-52",
    4: " Luke 23:27-31",
    5: " John 19:25-27",
    6: " John 19:38-40",
    7: " John 19:41-42"
  }
  swordscontext:{

    1: "The Blessed Virgin Mary took Jesus to the temple, as tradition demanded that all newborns be blessed in the temple before God. There, the old priest Simeon held the baby Jesus in his hands, and the Holy Spirit filled his heart. Simeon recognized Jesus as the promised Savior and held the child high toward heaven, thanking God for granting his wish that he would live long enough to behold the Messiah.<br> “Now Your servant may depart this life in peace, my Lord,” he said. Then he looked upon Mary and proclaimed, “And you, woman, a sword of sorrow will pierce your heart because of the suffering that shall befall your child.”<br>The Blessed Virgin knew that she had given birth to the Savior of humankind, so she immediately understood and accepted Simeon’s prophecy. Although her heart was deeply touched by this favor of bearing the baby Jesus, her heart remained heavy and troubled, for she knew what had been written about the ordeals and subsequent death of the Savior. Whenever she saw her son, she was constantly reminded of the suffering he would be subject to, and his suffering became her own.",
    2: "Mary’s heart broke and her mind was greatly troubled when Joseph revealed to her the words of the angel: they were to wake up quickly and flee to Egypt because Herod wanted to kill Jesus. The Blessed Virgin hardly had time to decide what to take or leave behind; she took her child and left everything else, rushing outside beforeJoseph so that they could hurry as God wished. Then she said, “Even though God has power over everything, He wants us to flee with Jesus, His son. God will show us the way, and we shall arrive without being caught by the enemy.”<br>Because the Blessed Virgin was the mother of Jesus, she loved him more than anyone else. Her heart was deeply troubled at the sight of her infant son’s discomfort, and she suffered greatly because he was cold and shivering. While she and her husband were tired, sleepy, and hungry during this long travel, Mary’s only thought was about the safety and comfort of her child. She feared coming face to face with the soldiers who had been ordered to kill Jesus because she was aware that the enemy was still in Bethlehem. Her heart remained constantly anguished during this flight. She also knew that where they were going, there would be no friendly faces to greet them.",
    3: "Jesus was the only begotten son of God, but he was also Mary’s child. The Blessed Virgin loved Jesus more than herself because he was her God. Compared to other children, he was most unique because he was already living as God. When Mary lost Jesus on their way back from Jerusalem, the world became so big and lonely that she believed she couldn’t go on living without him, so great was her sorrow. (She felt the same pain her son felt when he was later abandoned by his apostles during the Passion.)<br>As the Holy Mother looked anxiously for her beloved boy, deep pain welled in her heart. She blamed herself, asking why she didn’t take greater care of him. But it was not her fault; Jesus no longer needed her protection as before. What really hurt Mary was that her son had decided to stay behind without her consent. Jesus had pleased her in everything so far: he never annoyed her in any way, nor would he ever displease his parents. She knew that he always did what was necessary, however, so she never suspected him of being disobedient.",
    4: "Mary witnessed Jesus carrying the heavy cross alone—the cross on which he was to be crucified. This didn’t surprise the Blessed Virgin because she already knew about the approaching death of Our Lord. Noting how her son was already weakened by the numerous hard blows given by the soldiers’ clubs, she was filled with anguish at his pain. The soldiers kept hurrying and pushing him, though he had no strength left. He fell, exhausted, unable to raise himself. At that moment, Mary’s eyes, so full of tender love and compassion, met her son’s eyes, which were pained and covered in blood. Their hearts seemed to be sharing the load; every pain he felt, she felt as well. They knew that nothing could be done except to believe and trust in God and dedicate their suffering to Him. All they could do was put everything in God’s hands.",
    5: "The Blessed Virgin Mary continued to climb the mount to Calvary, following behind Jesus painfully and sorrowfully, yet suffering silently. She could see him staggering and falling with the cross some more, and she witnessed her son being beaten by soldiers who pulled his hair to force him to stand up. Despite his innocence, when Jesus reached the top of Calvary, he was ordered to confess in front of the crowd so they could laugh at him. Mary deeply felt her son’s pain and humiliation, particularly when his tormentors forced him to strip off what was left of his clothing. The Blessed Virgin felt sick at heart seeing these tyrants crucifying her son naked, shaming him terribly merely to amuse the jeering crowd. (Jesus and Mary felt more disgrace than normal people did because they were without sin and holy.) The Blessed Virgin Mary felt pain beyond bearing when Jesus was stretched out on the cross. His murderers sang merrily as they approached him with hammers and nails. They sat on him heavily so that he could not move when they spiked him to the wood. As they hammered the nails through his hands and feet, Mary felt the blows in her heart; the nails pierced her flesh as they tore into her son’s body. She felt her life fading away.<br>As the soldiers lifted the cross to drop it into the hole they’d dug, they deliberately jerked it, causing the force of Jesus’ bodily weight to tear through the flesh on his hands and expose his bone. The pain shot through his body like liquid fire. He endured three excruciating hours skewered on the cross, yet the physical pain was nothing compared to the agonizing heartache he was forced to bear seeing his mother suffering below him. Mercifully, he finally died.",
    6: "The friends of Jesus, Joseph and Nicodemus, took down his body from the cross and placed it in the outstretched arms of the Blessed Virgin. Then Mary washed it with deep respect and love because she was his mother. She knew better than anyone else that he was God incarnate who’d taken a human body to become the Savior of all people.<br>Mary could see the terrifying wounds from the flogging Jesus had received while at Pilate’s. His flesh had been shredded and large strips had been torn from his back. His entire body had been so lacerated that gaping wounds crisscrossed him from head to toe. Mary found that the wounds from the nails were less severe than those caused by the flogging and by carrying the cross. She was horrified at the thought that her son had managed to carry the heavy, splintered cross all the way to Calvary. She saw the circle of blood the crown of thorns had made on his forehead and, to her horror, realized that many of the barbed thorns had dug so deeply into his skull they had penetrated his brain. Looking at her broken boy, the Holy Mother knew that his agonizing death was far worse than the torture reserved for the wickedest of criminals. As she cleaned his damaged body she envisioned him during each stage of his short life, remembering her first look at his beautiful newborn face as they lay in the manger, and every day in between, until this heartrending moment as she gently bathed his lifeless body. Her anguish was relentless as she prepared her son and Lord for burial, but she remained brave and strong, becoming the true Queen of Martyrs. As she washed her son she prayed that everybody would know the riches of paradise and enter the gates of heaven. She prayed for every soul in the world to embrace God’s love, so her son’s torturous death would benefit all humankind and not have been in vain. Mary prayed for the world; she prayed for all of us.",
    7: "The life of the Blessed Virgin Mary was so closely linked to that of Jesus she thought there was no reason for her to go on living any longer. Her only comfort was that his death had ended his unspeakable suffering. Our sorrowful mother, with the help of John and the holy women, devoutly placed Jesus’ body in the sepulcher, and she left him there as any other dead person. She went home with great pain and tremendous sorrow; for the first time she was without him, and her loneliness was a new and bitter source of pain. Her heart had been dying since her son’s heart had stopped beating, but she was certain that our Savior would soon be resurrected."
  }
  prayers: {
    1: "Prayer: Beloved Mother Mary, whose heart suffered beyond bearing because of us, teach us to suffer with you and with love, and to accept all the suffering God deems it necessary to send our way. Let us suffer, and may our suffering be known to God only, like yours and that of Jesus. Do not let us show our suffering to the world, so it will matter more and be used to atone for the sins of the world. You, Mother, who suffered with the Savior of the world, we offer you our suffering, and the suffering of the world, because we are your children. Join those sorrows to your own and to those of the Lord Jesus Christ, then offer them to God the Father so that He will know the one who created it. You are a mother greater than all.",
    2: "Prayer: Beloved Mother, who has suffered so much, give to us your courageous heart. Give us strength so that we can be brave like you and accept with love the suffering God sends our way. Help us to also accept all the suffering we inflict upon ourselves and the suffering inflicted upon us by others. Heavenly Mother, you alone purify our suffering so that we may give glory to God and save our souls.",
    3: "Prayer: Beloved Mother, teach us to accept all our sufferings because of our sins and to atone for the sins of the whole world.",
    4: "Beloved Mother, so stricken with grief, help us to bear our own suffering with courage and love so that we may relieve your sorrowful heart and that of Jesus. In doing so, may we give glory to God Who gave you and Jesus to humanity. As you suffered, teach us to suffer silently and patiently. Grant unto us the grace of loving God in everything. O Mother of Sorrows, most afflicted of all mothers, have mercy on the sinners of the whole world.",
    5: "Prayer: Beloved Mother, Queen of the Martyrs, give us the courage you had in all your sufferings so that we may unite our sufferings with yours and give glory to God. Help us follow all His commandments and those of the Church so that Our Lord’s sacrifice will not be in vain, and all sinners in the world will be saved.",
    6: "Prayer: We thank you, Beloved Mother, for your courage as you stood beneath your dying child to comfort him on the cross. As our Savior drew his last breath, you became a wonderful mother to all of us; you became the Blessed Mother of the world. We know that you love us more than our own earthly parents do. We implore you to be our advocate before the throne of mercy and grace so that we can truly become your children. We thank you for Jesus, our Savior and Redeemer, and we thank Jesus for giving you to us. Please pray for us, Mother.",
    7: "Prayer: Most Beloved Mother, whose beauty surpasses that of all mothers, mother of mercy, mother of Jesus, and mother to us all, we are your children and we place all our trust in you. Teach us to see God in all things and all situations, even our sufferings. Help us to understand the importance of suffering, and also to know the purpose of our suffering as God had intended it.<br>You yourself were conceived and born without sin, were preserved from sin, yet you suffered more than anybody else has. You accepted suffering and pain with love and with unsurpassed courage. You stood by your son from the time he was arrested until he died. You suffered along with him, felt every pain and torment he did. You accomplished the will of God the Father; and according to His will, you have become our savior with Jesus. We beg you, dear Mother, to teach us to do as Jesus did. Teach us to accept our cross courageously. We trust you, most merciful mother, so teach us to sacrifice for all the sinners in the world. Help us to follow in your son’s footsteps, and even to be willing to lay down our lives for others."
  }
  promises:{
    1: "1. I will grant peace to their families.",
    2: "2. They will be enlightened about the Divine Mysteries.",
    3: "3. I will console them in their pains and I will accompany them in their work.",
    4: "4. I will give them as much as they ask for as long as it does not oppose the adorable will of my Divine Son or the sanctification of their souls.",
    5: "5. I will defend them in their spiritual battles with the infernal enemy and I will protect them at every instant of their lives.",
    6: "6. I will visibly help them at the moment of their death - they will see the face of their mother.",
    7: "7. I have obtained this grace from my Divine Son, that those who propagate this devotion to my tears and Sorrows will be taken directly from this earthly life to eternal happiness, since all their sins will be forgiven and my Son will be their eternal consolation and joy."
  }

}


